build:
  stage: build
  script:
    - docker build -t toolbox .

test:
  stage: test
  script:
    - docker run toolbox docker-machine version
    - docker run toolbox docker-compose version
    - docker run toolbox docker version

deploy:
  stage: deploy
  script:
    - docker tag -f toolbox schmunk42/docker-toolbox
    - docker push schmunk42/docker-toolbox