before_script:
  - export COMPOSE_PROJECT_NAME=buildpipeline${CI_PIPELINE_ID}
  - docker-compose ps

after_script:
  - export COMPOSE_PROJECT_NAME=buildpipeline${CI_PIPELINE_ID}
  - docker-compose down -v

test:
  stage: test
  script:
    - docker-compose build --pull
    - docker-compose run --rm toolbox ls -la /opt/local/bin
    - docker-compose run --rm toolbox docker-machine version
    - docker-compose run --rm toolbox docker --version
    - docker-compose run --rm toolbox docker-compose version
    - docker-compose run --rm toolbox docker-cloud --version
