before_script:
  - export COMPOSE_PROJECT_NAME=buildpipeline${CI_PIPELINE_ID}
  - docker-compose ps

after_script:
  - docker-compose ps

build:
  stage: build
  script:
    - docker-compose build --pull

test:
  stage: test
  script:
    - docker-compose run --rm toolbox docker-machine version
    - docker-compose run --rm toolbox docker --version
    - docker-compose run --rm toolbox docker-compose version
