build:
  script:
    - docker build -t toolbox .

test:
  script:
    - docker run toolbox docker-machine version
    - docker run toolbox docker-compose version
    - docker run toolbox docker version

deploy:
  script:
    - docker tag toolbox schmunk42/docker-toolbox
    - docker push schmunk42/docker-toolbox